# Copyright (C) 2023 Christian Berger
#
# Using the latest Docker image and Docker-in-Docker service to ensure compatibility with Docker Engine 26.1.1.

image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-and-test:
  stage: build
  only: 
    - branches
  tags:
    - docker-build
  script:
    - docker build -f Dockerfile .

release:
  stage: deploy
  when: on_success
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
  tags:
    - docker-build
  script:
    - echo "Deploying tag $CI_COMMIT_TAG to $CI_REGISTRY_IMAGE"
    - docker build -f Dockerfile -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG"